---
- hosts: all
  vars_files:
    - vars.yaml

  tasks:
    - name: Install applications {{pkg}}
      apt: 
       name: "{{pkg}}"
       state: present

    - name: Create user {{usr}}
      user:
       name: "{{usr}}"
       state: present
